title: Leamin
email: avaglir@gmail.com
description: >-
  A site for our D&D campaign.
baseurl: /leamin
url: /leamin
author: mammothbane
github_username:  mammothbane

google_analytics: UA-123406315-1

markdown: kramdown
plugins:
  - jekyll-seo-tag

sass:
  sass_dir: _scss

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
